---
title: "p8105_hw3_jy3186"
author: "Jiayi Yang"
date: "2022-10-11"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
```
##Problem 2
load and tidy the data 
```{r}
accel_data = read_csv("./accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    weekday_weekend = ifelse(day %in% c("Saturday","Sunday"), "Weekend", "Weekday"),
    day_id = as.integer(day_id),
    week = as.integer(week)
  ) %>% 
  relocate(weekday_weekend)
accel_data
```
There are `r nrow(accel_data)` observations and `r ncol(accel_data)` variables.
There are four date variables `weekday_weekend`, `week`, `day_id` and `day`; and 1440 variables of activity observations.

aggregate activities and make a plot to show the trend
```{r}
accel_data %>% 
  group_by(day_id) %>% 
  mutate(
    activity_total =  sum(across(activity_1:activity_1440), na.rm = TRUE),
    activity_total = as.integer(activity_total)
  ) %>% 
  select(week, day, day_id, activity_total) %>% 
  ggplot(aes(x = day_id, y = activity_total, color = day)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```
Make a single-panel plot that shows the 24-hour activity time courses for each day
```{r}
accel_eachday = accel_data %>% 
  select(day_id, day, week, activity_1:activity_1440) %>% 
  pivot_longer(activity_1:activity_1440, names_to = "activity_min", values_to = "activity_value") %>% 
  separate(activity_min, c( NA, "activity"), sep = "_") %>% 
  mutate(
    activity = as.integer(activity)
  ) %>% 
  ggplot(aes(x = activity, y = activity_value, color = day), se = FALSE) + 
    geom_point() + geom_line(alpha = .5) + geom_smooth(aes(group = day), se = FALSE) +
    labs(
    title = "24-hour activity plot for each day",
    x = "minute",
    y = "activity value at the minute"
  ) + 
    theme(legend.position = "bottom")
accel_eachday
```

## R Markdown

